---

- hosts: all
  become: true
  gather_facts: true
  #  roles:
  #    - base-preseed

  tasks:

    - name: "Update all Packages on (Debian/Ubuntu))"
      apt: 
        upgrade=full
        update_cache=yes
      when: ansible_os_family == "Debian"

...
